# Generated by Django 3.2.9 on 2022-06-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='level',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='level',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Уровень'),
        ),
    ]
