# Generated by Django 3.2.9 on 2022-04-25 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0001_initial'),
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': 'Права', 'verbose_name_plural': 'Права'},
        ),
        migrations.AlterField(
            model_name='permission',
            name='targetCourseId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.course', verbose_name='Course ID цели доступа'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='targetCourseIdKey',
            field=models.CharField(blank=True, choices=[('OWN_ID', 'Own Id'), ('TEACH_COURSES_IDS', 'Teach Courses Ids')], max_length=255, null=True, verbose_name='Ключ course ID цели доступа'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='targetUserId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to=settings.AUTH_USER_MODEL, verbose_name='User ID цели доступа'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='targetUserIdKey',
            field=models.CharField(blank=True, choices=[('OWN_ID', 'Own Id'), ('TEACH_COURSES_IDS', 'Teach Courses Ids')], max_length=255, null=True, verbose_name='Ключ user ID цели доступа'),
        ),
    ]
