# Generated by Django 3.2.9 on 2022-04-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_auto_20220425_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='targetCourseIdKey',
            field=models.CharField(blank=True, choices=[('OWN_ID', 'Own Id'), ('MY_COURSES_IDS', 'My Courses Ids'), ('TEACH_COURSES_IDS', 'Teach Courses Ids')], max_length=255, null=True, verbose_name='Ключ course ID цели доступа'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='targetUserIdKey',
            field=models.CharField(blank=True, choices=[('OWN_ID', 'Own Id'), ('MY_COURSES_IDS', 'My Courses Ids'), ('TEACH_COURSES_IDS', 'Teach Courses Ids')], max_length=255, null=True, verbose_name='Ключ user ID цели доступа'),
        ),
    ]
