# Generated by Django 3.2.9 on 2022-04-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_auto_20220425_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='targetCourseIdKey',
            field=models.CharField(blank=True, choices=[('OWN_ID', 'Own Id'), ('STUDY_COURSES_IDS', 'Study Courses Ids'), ('TEACH_COURSES_IDS', 'Teach Courses Ids')], max_length=255, null=True, verbose_name='Ключ course ID цели доступа'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='targetUserIdKey',
            field=models.CharField(blank=True, choices=[('OWN_ID', 'Own Id'), ('STUDY_COURSES_IDS', 'Study Courses Ids'), ('TEACH_COURSES_IDS', 'Teach Courses Ids')], max_length=255, null=True, verbose_name='Ключ user ID цели доступа'),
        ),
    ]
