# Generated by Django 3.2.9 on 2021-11-17 13:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0013_student_teacher'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Группа')),
                ('price', models.PositiveIntegerField(default=0, help_text='указывать цену в рублях', verbose_name='Цена')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='languages.language', verbose_name='Язык')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='languages.level', verbose_name='Уровень')),
                ('student', models.ManyToManyField(to='auth.Student', verbose_name='Студент')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время занятия')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Домашнее задание')),
                ('url', models.URLField(blank=True, null=True)),
                ('descrition', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('deadline', models.DateTimeField(default=datetime.datetime(2021, 11, 18, 13, 33, 7, 206028, tzinfo=utc), verbose_name='Дата дедлайна')),
                ('durable', models.BooleanField(default=False, verbose_name='Длительное')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
            },
        ),
    ]
