# Generated by Django 3.2.9 on 2021-11-17 13:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_student_teacher'),
        ('languages', '0001_initial'),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='homework',
            old_name='group',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='group',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='homework',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 13, 41, 32, 284265, tzinfo=utc), verbose_name='Дата дедлайна'),
        ),
    ]
