# Generated by Django 3.2.9 on 2022-05-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0016_alter_userprofile_role'),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, to='auth.Student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='указывать цену в рублях', null=True, verbose_name='Цена'),
        ),
    ]
