# Generated by Django 3.2.9 on 2022-06-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='course',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='homework',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='homework',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='homework',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='homework',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
    ]
