# Generated by Django 3.2.9 on 2022-04-25 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_student_teacher_userprofile'),
        ('education', '0002_auto_20220425_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(to='auth.Student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.teacher', verbose_name='Учитель'),
        ),
    ]
