# Generated by Django 3.2.9 on 2021-11-17 13:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20211117_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 13, 43, 2, 914442, tzinfo=utc), verbose_name='Дата дедлайна'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.course', verbose_name='Курс'),
        ),
    ]
