# Generated by Django 3.2.9 on 2022-06-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20220610_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='end',
            field=models.DateTimeField(max_length=350, verbose_name='Дата окончания занятия'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='period',
            field=models.PositiveIntegerField(max_length=350, verbose_name='Промежуток между занятиями периода'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='starts',
            field=models.DateTimeField(max_length=350, verbose_name='Дата и время первого занятия'),
        ),
    ]
