# Generated by Django 3.2.9 on 2021-11-24 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20211117_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 25, 14, 10, 5, 228069, tzinfo=utc), verbose_name='Дата дедлайна'),
        ),
    ]
