# Generated by Django 3.2.9 on 2021-11-24 16:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_alter_homework_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 25, 16, 40, 49, 708340, tzinfo=utc), verbose_name='Дата дедлайна'),
        ),
    ]
