# Generated by Django 3.2.9 on 2022-01-10 14:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_alter_homework_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 14, 9, 38, 837919, tzinfo=utc), verbose_name='Дата дедлайна'),
        ),
    ]
