# Generated by Django 3.2.9 on 2022-01-30 15:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_alter_homework_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 15, 20, 50, 106120, tzinfo=utc), verbose_name='Дата дедлайна'),
        ),
    ]
