# Generated by Django 3.2.9 on 2022-02-03 07:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_auto_20220130_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 7, 53, 6, 393990, tzinfo=utc), verbose_name='Дата дедлайна'),
        ),
    ]
