# Generated by Django 3.2.9 on 2022-02-03 08:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_alter_homework_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 8, 13, 46, 906140, tzinfo=utc), verbose_name='Дата дедлайна'),
        ),
    ]
