# Generated by Django 3.2.9 on 2022-02-03 08:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_alter_homework_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 8, 20, 39, 278716, tzinfo=utc), verbose_name='Дата дедлайна'),
        ),
    ]
